#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---
# Z3ST: An open-source FEniCSx framework for thermo-mechanical analysis
# Author: Giovanni Zullo
# Version: 0.3.2 (2026)
# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---
"""
Writes ``boundary_conditions.yaml`` for one loading angle.

The strength-surface test drives the block through a homogeneous strain state
whose ratio is set by the angle Theta (paper Sec. 5.3): opposing edges are
pulled apart by ``+/- U_t cos(Theta)`` in x and ``+/- U_t sin(Theta)`` in y, so
that ``eps_xx = 2 U_t cos(Theta) / L`` and ``eps_yy = 2 U_t sin(Theta) / L``.
Sweeping Theta therefore sweeps the stress space, and the stress at which the
phase field first becomes non-zero traces the strength surface.

The phase field is pinned to zero along every edge to keep nucleation away from
the boundary, where the Dirichlet layer would bias it.

Used both by this case (one angle, checked against Eq. 110) and by sweep.py,
which reruns the case over many angles to reconstruct the whole surface.
"""

import os

import numpy as np

CASE_DIR = os.path.dirname(os.path.abspath(__file__))

HEADER = """# Generated by make_bc.py -- edit that, not this file.
# Loading angle Theta = {theta_deg:.4f} deg, U_t ramped to {u_max:.6e} m
# in {n_steps} steps. eps_xx / eps_yy = cot(Theta) is what selects the point
# of the strength surface this run probes.
"""


def write(theta_deg, u_max, n_steps, path=None):
    """Write the BC file for one angle; returns the path."""
    theta = np.radians(theta_deg)
    ramp = np.linspace(u_max / n_steps, u_max, n_steps)
    ux, uy = ramp * np.cos(theta), ramp * np.sin(theta)

    lines = [HEADER.format(theta_deg=theta_deg, u_max=u_max, n_steps=n_steps),
             "mechanical:", "  block:"]
    for region, values, axis in (("right", ux, "x"), ("left", -ux, "x"),
                                 ("top", uy, "y"), ("bottom", -uy, "y")):
        lines += [f"  - type: Dirichlet_{axis}", f"    region: {region}",
                  "    displacement:"]
        lines += [f"    - {v:.10e}" for v in values]

    # Phase field held at zero on the boundary.
    lines += ["", "damage:", "  block:"]
    for region in ("bottom", "right", "top", "left"):
        lines += ["  - type: Dirichlet", f"    region: {region}", "    value: 0.0"]

    path = path or os.path.join(CASE_DIR, "boundary_conditions.yaml")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


if __name__ == "__main__":
    import sys

    theta = float(sys.argv[1]) if len(sys.argv) > 1 else 99.83
    u_max = float(sys.argv[2]) if len(sys.argv) > 2 else 7.0e-5
    steps = int(sys.argv[3]) if len(sys.argv) > 3 else 200
    print(f"[INFO] wrote {write(theta, u_max, steps)}")
